const data = {
  products: [
    {
      _id: '1',
      name: 'Gold-Floral-ring',
      slug: 'gold-floral-ring',
      category: 'rings',
      image: '/images/ring1.jpg',
      price: "3647.00",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Great design ring',
    },
    {
      _id: '2',
      name: 'Gold-Heart-ring',
      slug: 'gold-heart-ring',
      category: 'rings',
      image: '/images/ring2.jpg',
      price: "2643.00",
      countInStock: 0,
      rating: 3.0,
      numReviews: 10,
      description: 'Great design ring',
    },
    {
      _id: '3',
      name: 'Gold-Daisy-ring',
      slug: 'gold-daisy-ring',
      category: 'rings',
      image: '/images/ring3.jpg',
      price: "1999.00",
      countInStock: 20,
      rating: 4.3,
      numReviews: 10,
      description: 'Great design ring',
    },
    {
      _id: '4',
      name: 'Gold-Ohm-ring',
      slug: 'gold-ohm-ring',
      category: 'rings',
      image: '/images/ring4.jpg',
      price: "2999.00",
      countInStock: 10,
      rating: 3.7,
      numReviews: 8,
      description: 'Great design ring',
    },
  ],
};
export default data;
