const data = {
  products: [
    {
      id: '001',
      name: 'Gold-Floral-ring',
      category: 'rings',
      image: require('./images/ring1.jpg'),
      price: '3,647.00',
      qualit: '916',
      rating: '4.5',
      numReviews: '10',
      description: 'Great design ring',
    },
    {
      id: '002',
      name: 'Gold-Heart-ring',
      category: 'rings',
      image: require('./images/ring2.jpg'),
      price: '2,643.00',
      qualit: '916',
      rating: '3.0',
      numReviews: '10',
      description: 'Great design ring',
    },
    {
      id: '003',
      name: 'Gold-Daisy-ring',
      category: 'rings',
      image: require('./images/ring3.jpg'),
      price: '1,999.00',
      qualit: '916',
      rating: '4.3',
      numReviews: '10',
      description: 'Great design ring',
    },
    {
      id: '004',
      name: 'Gold-Ohm-ring',
      category: 'rings',
      image: require('./images/ring4.jpg'),
      price: '2,999.00',
      qualit: '916',
      rating: '3.7',
      numReviews: '8',
      description: 'Great design ring',
    },
  ],
};
export default data